name: Build and Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.14.0'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build --prod

      - name: Deploy to gh pages
        run: |
          npx angular-cli-ghpages --dir=dist/car-rent
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
    #*- name: Deploy to GitHub Pages
    #    uses: peaceiris/actions-gh-pages@v3
    #    with:
    #      github_token: ${{ secrets.GH_TOKEN }}
    #      publish_dir: ./dist/car-rent

      #- name: Deploy to Azure
      #  uses: azure/webapps-deploy@v2
      #  with:
      #    app-name: <YOUR_APP_NAME>
      #    slot-name: production
      #    publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
      #    package: ./dist/<YOUR_APP_NAME>.